version: "3"

volumes:
    mysqldata:
    mysqlinit:
    app:

services:
    php:
        build: ./php
        ports:
            - 12320:80
        volumes:
            - ./app:/var/www/html

    mysql:
        image: mysql:latest
        ports:
            - 3306:3306
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: mensaUser
            MYSQL_PASSWORD: userpass
            MYSQL_DATABASE: mensa
        volumes:
            - ./mysql/initscripts:/docker-entrypoint-initdb.d
            - ./mysql/mysqldata:/var/lib/mysql/

    adminer:
        image: adminer
        ports:
            - 8080:8080
