site_name: M133 - PHP

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  language: de
  logo: favicon.svg
  favicon: favicon.svg
  font:
    text: Roboto
  icon:
    repo: fontawesome/brands/github-alt
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - navigation.indexes
    - search.share
    - content.code.annotate
    - content.tabs.link

extra_css:
  - css/custom.css

copyright: Copyright &copy; 2022 Manuel Schumacher

repo_url: https://github.com/bztfinformatik/lernportfolio-21r8390-php
repo_name: 21r8390/Sourcecode
edit_uri: https://github.com/bztfinformatik/lernportfolio-21r8390-php/tree/main/docs

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/bztfinformatik/lernportfolio-21r8390-php
      name: 21r8390 on GitHub

markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: "#"
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji

  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.snippets:
      base_path: docs
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search:
      lang:
        - de
  - tags:
      tags_file: "Tags.md"
  - minify:
      minify_html: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
      css_files:
        - "css/custom.css"
  - redirects:
      redirect_maps:
        "PHP/UEbersicht.md": "PHP/Start.md"
        "Appendix/PHP-Cheatsheet.md": "PHP/Cheatsheet.md"
        "Appendix/Changelog.md": "Changelog.md"
        "Appendix/Tags.md": "Tags.md"

nav:
  - Startseite:
      - Startseite: "index.md"
      - Changelog: "Changelog.md"
      - Tags: "Tags.md"
  - Reflexion:
      - "1. Woche": "Reflexion/001_Woche.md"
  - PHP:
      - Übersicht: "PHP/Start.md"
      - Installation: "PHP/Installation.md"
      - Basics: "PHP/Basics.md"
      # - Datenbanken: "PHP/Datenbanken.md"
      # - Session:
      # - Authorization:
  - Docker:
      - Übersicht: "Docker/Start.md"
  - Projekt:
      - Ziel: "Projekt/Ziel.md"
      - Mockup: "Projekt/Planung.md"
      - Selbstreflexion: "Projekt/Selbstreflexion.md"
  - Appendix:
      - PHP-Cheatsheet: "PHP/Cheatsheet.md"
